### ISSUE TITLE
[UI issue] Pomodoro Timer | Better placement of the description

### ISSUE THREAD

**Issue by SchaffRita** [Ayagikei/LifeUp#10]
**🧪 Test Environment**

**LifeUp version**: 1.83.5 (225)
**Android Version**: 6.0.1 / 10
**OS**: MIUI Global 10.2 / Magic UI 4.0.0

* * *

**📝 Steps to Reproduce**

1. Start LifeUp
2. Make sure to use the English language
3. Click on the Menu bar in the upper left corner
4. Click on **Pomodoro**
5. Click on **Selling Price of Tomato**
6. Inspect the text _Tap the number in the center to directly input the target value_

✔️ **Expected Results**: the visible text is placed in a way so it would have some borders.
❌ **Actual Results**: the visible text reaches out till the borders of the popup.

![image](https://user-images.githubusercontent.com/50463942/120885643-41afee00-c5ea-11eb-85ea-6c8c0b9f645a.png)

**Comment by SchaffRita** [comment]
@Ayagikei Please let me know if this format of submitting issues works for you.
If you let me tag issues, I can also do that.

**Comment by Ayagikei** [comment]
@SchaffRita 
Thanks for the feedback, the format and information are perfect.

For UI issues, part of the information can be simply skipped. Of course, the more complete the information, the better.
We will investigate and follow up on this issue, and it will be fixed in the next version.

By the way, the LifeUp version should not contain "Beta". 
Google Play’s Beta channel will also push a newer official version. The display on the "About" page should be more accurate.

**Comment by SchaffRita** [comment]
Hi @Ayagikei , thanks for the quick feedback.

> By the way, the LifeUp version should not contain "Beta".
I wasn't sure that the version `(225)` would show you the version I'm on, this is why I added `beta`. I modified my issues, I will only include the correct version from now on.

For the next UI issues, I will skip the unnecessary steps.
If you want, I can also create video recordings of issues that have multiple steps - let me know what you prefer.
Thanks!

**Comment by Ayagikei** [comment]
> Hi @Ayagikei , thanks for the quick feedback.
> 
> > By the way, the LifeUp version should not contain "Beta".
> > I wasn't sure that the version `(225)` would show you the version I'm on, this is why I added `beta`. I modified my issues, I will only include the correct version from now on.
> 
> For the next UI issues, I will skip the unnecessary steps.
> If you want, I can also create video recordings of issues that have multiple steps - let me know what you prefer.
> Thanks!

Good to hear that.
The version code (225) is enough for us to locate the version.

Video is also a good way of feedback, it is suitable for complex steps and phenomena.
Thanks again for assisting in testing and feedback.

**Comment by Ayagikei** [comment]
It should be already fixed in version 1.83.7
