### ISSUE TITLE
[Bug] Titles of attribute actions Disable and Delete are exchanged

### ISSUE THREAD

**Issue by LordElamak** [Ayagikei/LifeUp#104]
**Describe the bug**
The Title "Disable" appears in attribute delete action window and "Delete" in the attribute disable action window.
Please see attached screenshots.
![SmartSelect_20231017_145447_LifeUp Pro](https://github.com/Ayagikei/LifeUp/assets/144832912/6f3cbf30-6a51-4cb2-af03-4485e7a73cbb)
![SmartSelect_20231017_145520_LifeUp Pro](https://github.com/Ayagikei/LifeUp/assets/144832912/984d497c-49ec-4fab-b2de-f5aba3413b5b)

**Comment by Ayagikei** [comment]
Thanks for the report!

**Comment by Ayagikei** [comment]
This problem should have been fixed in v1.93.0-rc02.

If the problem persists, please feel free to open the issue again.
