### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by WilliamVoitsekhovskyi** [Ayagikei/LifeUp#114]
**Not correct displaying attributes**
In the attached screenshot

**To Reproduce**
1. Go to attributes 
2. Create attributes to fill the whole screen
3. Scroll down

**Expected behavior**
Displaying above buttons-panel

**Screenshots**
![Screenshot_20231221_183625_LifeUp Pro.jpg](https://github.com/Ayagikei/LifeUp/assets/45714708/c53514c3-2b94-4260-8b9d-608970ffca99)

**Environments and Version (please complete the following information):**
 - Device: [e.g. S23 ultra]
 - OS: [e.g. Android 14.0]
 - Version [1.93.3 (532) ]

**Additional context**

**Comment by Ayagikei** [comment]
Thanks for your feedback!

We have successfully reproduced the issue and it will be fixed in the next version.

**Comment by Ayagikei** [comment]
It should have been fixed in version 1.93.4.
