### ISSUE TITLE
Inventory Coins 

### ISSUE THREAD

**Issue by veepsa** [Ayagikei/LifeUp#126]
![Screenshots_2024-01-18-17-34-32](https://github.com/Ayagikei/LifeUp/assets/155193473/736a65eb-bc19-433d-adc6-5f00c2cbfb59)

What are the inventory coins for? I can't seem to be able use them to purchase any rewards in the shop, so what do I do with them? Right now, I have 100 coins in the inventory & I can't for the life of me understand how I got them & what their purpose is. 

Can anyone help?

Thank you! :)

**Comment by Ayagikei** [comment]
- This is the number of coins you have, and this number will be displayed on the shop and inventory pages.
- You can use coins to purchase items in the shop. Items in the shop support customization of purchase availability and price.
- Some items used may also increase or decrease the number of coins you have.

**Comment by Ayagikei** [comment]
You are also welcome to check out the section about Shop in our novice tutorial: https://docs.lifeupapp.fun/en/#/guide/hello_lifeup?id=-linkage-1

**Comment by veepsa** [comment]
Hi, thank you so much for your reply, & thank you for this amazing app! It
is so multifunctional, I love it!

I got one more question. I would like to set a repeating task that acts as
a counter, but I would like to get a coin reward each time I complete a
repetition. Is it possible?

For example, say I want to drink water 5 times a day, but instead of
getting the reward only upon completion of the entire set, I want to get a
reward after every time I drink a glass of water.

Thanks again & have a great day!

**Comment by veepsa** [comment]
OK, never mind. I figured it out. I can do it by assigning coins to
subtasks. Thanks anyway!
