### ISSUE TITLE
[Feature] API to directly create inventory items

### ISSUE THREAD

**Issue by DariALV** [Ayagikei/LifeUp#131]
### **Is your feature request related to a problem? Please describe.**
I'm trying to create a gacha-like pokemon object to put on the market, with the use of Tasker, but since there are many pokemon, I cant use lootboxes for that matter, I just want to create an object with a pokemon data extracted from the PokeAPI, then add it to the inventory when another item is purchased. (Kinda like a lootbox without manually setting up the items, since they wont be added to the shop).

### **Describe the solution you'd like**
I want an API that adds items directly to the inventory, instead of the shop.

### **Describe alternatives you've considered**
The only workaround I found is to set the stock amount of the pokemon to 1, so after the user purchases the lootbox, a pokemon item is added to the shop, then bought and it just sticks there, sold out, which is kinda frustrating.

**Comment by DariALV** [comment]
In addition, I don't how does the predefined item "Coin loot box" work, but something like that would also be nice, to have the pokemon (Or any gacha item to generalize the problem)  be added in a lootbox (Maybe using the lootbox API) without it being part of the shop. The "Coin loot box" has a chance to give 2 items, "A big bag of coins" and "A small bag of coins", but none of those are present in the shop, and I can't recreate this effect. 

It would be nice to have, so you can have kind of collectibles, and track the amount of collectibles you've got, with an achievement, a stat or something else, but I'm having it rough to recreate obtaining collectibles smoothly.

**Comment by Ayagikei** [comment]
Sorry for the late reply!

The predefined item "Coin loot box" in LifeUp is actually a item that has been removed from the shelves(shop), but it still has inventory.

We will consider adding an `unlist` parameter to the `add_item` API and adding a dedicated `unlist_item` API to help solve this scenario.

**Comment by Ayagikei** [comment]
The corresponding parameters have been added in v1.94.0.
