### ISSUE TITLE
[Feature] API. Complete "Count" Task 

### ISSUE THREAD

**Issue by KokhanOksana** [Ayagikei/LifeUp#132]
There is no possibility to complete or update a "Count" type Task from API.

I call "lifeup://api/complete..." API with any query parameter (id, gid, name) for a Count task.
Task is not completed, count is not changed. A popup is displayed in the app to enter count.

It would be great to add "count" parameter to the query, so "Count" task can be updated from API.
As an alternative, a "count"  for the task can increase by 1 with the current API call.

**Comment by Ayagikei** [comment]
Thanks for the issue!

Count-related parameters for the completion task API have been provided in v1.94.

![image](https://github.com/Ayagikei/LifeUp/assets/29143057/7f1bf152-20f9-4dc5-8719-4d8eb91da89e)
