### ISSUE TITLE
[Use Item Dialog URL Not Working]

### ISSUE THREAD

**Issue by HunterArmstrong** [Ayagikei/LifeUp#144]
**Use Item Dialog Window Not Popping Up on URL Press**

**To Reproduce**
1. Go to 'Tasker'
2. Click on 'Tasks'
3. Click on the add button
4. Type 'New Task'
5. Click on the add button 
6. Go to 'Browse URL'
7. Under 'URL', Type 'lifeup://api/goto?page=use_item_dialog&id=1'
8. Go back to the new task
9. Click the play button
10. Clicking the play button should access the 'Use Item' popup window. But it doesn't do that

**Expected behavior**
I expected there to be a 'Use Item' popup immediately after I clicked the play button when I was using the URL in Tasker

**Comment by Ayagikei** [comment]
Hello, we confirmed that calling the API through Item within the application is working.

Please note that this API was launched in version v1.94.0 (including the rc version).

This version is still being released on a rolling basis, and some users may still not receive the update.

Please confirm the app version, and try to use the Item effect in the app to see if it works, and try different item IDs.
