### ISSUE TITLE
[Bug] Unable to show or hide the tool bar by dragging the screen

### ISSUE THREAD

**Issue by WantenMN** [Ayagikei/LifeUp#152]
**Describe the bug**

The yellow area I call the tool bar, and the red area I call the drag area: 

![Screenshot_20240603_002737](https://github.com/Ayagikei/LifeUp/assets/41904684/729b8b02-f4eb-49bb-9f24-bf1892c4b6f9)

The problem I encountered is that I can't show or hide the yellow by dragging the red area.

I hide the tool bar in one task list, and then select another task list. If there are few tasks in this task list, the red area will almost fill the entire screen, making it impossible to display the tool bar by dragging most of the screen, so I will not be able to use features such as search, calendar, and side bar.

**To Reproduce**
1. Go to the task list application.
2. Hide the toolbar in a task list with many tasks.
3. Switch to another task list that has very few tasks.
4. Observe that the red area fills almost the entire screen, making it difficult or impossible to show the toolbar by dragging the red area.

**Expected behavior**
The toolbar should be accessible even when switching to a task list with few tasks. Dragging the red area should always allow the user to show or hide the toolbar, regardless of the number of tasks in the list. This ensures that features such as search, calendar, and the sidebar remain usable at all times.

**Screenshots**
Above.

**Environments and Version (please complete the following information):**
 - Device: Pixel 7
 - OS: Android 14
 - Version 1.95.0-rc01 (563)

**Additional context**
None.

**Comment by Ayagikei** [comment]
Thanks for the feedback!

We have found that the problem is due to the height of the list (RecyclerView) not meeting expectations.

This can also cause some animation anomalies.

We have tried to fix the issue in v1.95.0 (573).
