### ISSUE TITLE
[Bug] Freezing after dismissing overdue tasks panel

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [Ayagikei/LifeUp#161]
**Describe the bug**
The app frequently freezes when closing the overdue tasks panel, ultimately culminating in an ANR ("LifeUp Pro isn't responding" or something like that) dialog. I suspect this relates to logic dealing with the dialog that would normally appear afterwards, because the freezing seems to occur before that appears.

**Environments and Version (please complete the following information):**
 - Device: **Samsung Galaxy S24**
 - OS: **One UI 6.1 (Android 14)**
 - App Version: **1.95** (573)

**Additional context**
The issue goes back several updates.

**Comment by Ayagikei** [comment]
We'll troubleshoot the issue.

**Comment by UsernamesAreNotMyThing** [comment]
Doesn't appear to be happening anymore.
