### ISSUE TITLE
[Feature]Stats widget

### ISSUE THREAD

**Issue by HunterArmstrong** [Ayagikei/LifeUp#19]
**Is your feature request related to a problem? Please describe.**
I think that it would be nice to have a statistics widget that would display your level, attributes, coins, etc

**Describe the solution you'd like**
A widget that displays your stats

**Comment by SchaffRita** [comment]
> But we haven't done the UI design yet. **If anyone wants to contribute a design, please reply to me or contact me by email.**
I would like to apply. ✋

**Comment by HunterArmstrong** [comment]
Currently working on a widget like this thanks to the API feature alongside the **Tasker** app and the **KWGT** app (which has Tasker integrated). I still appreciate the response you made to this request I made over a year ago! :)

**Comment by Ayagikei** [comment]
> Currently working on a widget like this thanks to the API feature alongside the **Tasker** app and the **KWGT** app (which has Tasker integrated). I still appreciate the response you made to this request I made over a year ago! :)

Glad it works!

I'm sorry that this request has been placed for a long time, we have added built-in widgets to the development roadmap, but it may still take a while.

For APIs, it's good to see that they can address this need. We are also preparing to provide an SDK. It will be more convenient for the community to directly obtain relevant information about attributes through the SDK and develop widgets directly.

**Comment by Ayagikei** [comment]
We have released the first batch of status widgets in v1.91.0.

We are planning more status widgets and in-app stats in subsequent releases. Stay tuned :D!
