### ISSUE TITLE
任务绑定奖励+成就

### ISSUE THREAD

**Issue by LittlePuddingEye** [Ayagikei/LifeUp#2]
可以增加这两个功能吗：

1. 任务绑定奖励：
比如商店里有一张奶茶券，在设置任务的时候可以把任务的完成奖励直接关联到奶茶券，这样完成任务后仓库里直接就多了一张奶茶券。
这样的话我平时设置很多绑定商品的任务，一段时间后仓库里就会多出来很多东西，可能自己都不记得总共拿到了哪些奖励。没事干的时候就去仓库随便挑点东西使用一下，就像大扫除的时候翻出一大堆以前的宝贝一样。

2. 自定义成就：
对一些不停重复的任务，比如累计完成10次“每日画画”任务就达成“绘画初阶”成就。这个成就绑定金币和特定商品，达成成就后直接得到金币和商品奖励。

（我居然跑过来问开发者要功能，会不会很冒犯啊）

**Comment by LittlePuddingEye** [comment]
现在的版本也可以设置完成奖励，但这个奖励是手动输入的，而不是在已有商品列表里选一个。而且这个奖励不会被记录，不能在仓库里长期保存。

**Comment by Ayagikei** [comment]
谢谢建议~闭源之后，本来也打算把这里当作提建议的地方的。

关于第一点。近期有意开发这个功能。最近Google Play上也有个反馈提到了这个问题。其实目前的“完成奖励”是在开发商店系统之前的产物，所以没和商店、仓库结合起来。

第二点。自定义成就目前也有意开发。不过我之前设想的是大型待办事项（即大型的目标，月目标、年目标）。看了你的建议，觉得也可以加上设定自定义完成条件（选择完成某个待办事项xx次等）。
建议很棒！
自定义成就的开发可能有一定工作量，可能需要一段时间开发。

如果未来有其他建议也欢迎提议。

**Comment by Ayagikei** [comment]
抱歉，过了这么久才初步实现功能。

v1.74.0版本目前已经支持了任务绑定奖励，自定义成就也有初步实现。
不过目前自定义成就的“完成”仍需要用户手动操作，还没实现用户设置条件，然后自动完成。此外还少了成就绑定奖励的功能。这些后续会考虑扩展上，先关闭 issue 了~
