### ISSUE TITLE
[Bug] 错误的编辑界面

### ISSUE THREAD

**Issue by NeosXu** [Ayagikei/LifeUp#20]
**描述问题**
在列表视图中，比如主视图的任务列表、成就视图的成就列表等，长按一个项（称为项1），如果再点击另一个项（称为项2）并取消选择之前的项（项1），然后点击右上角的编辑按钮。这时任务视图中是选择了项2并点击对项2的编辑按钮，但是打开的编辑视图是对项1进行编辑的的视图，而不是项2的。

**如何复现该问题**
操作如下:
1. 进入页面 '委托'
2. 长按一个项（项1）
3. 点击另一个项（项2）
4. 点击项1
5. 点击右上角编辑按钮
6. 出现与预期不符的编辑页面

**预期表现**
在问题描述的情况中，期望打开的是项2的编辑页面，而不是项1的编辑页面。

**环境信息 (请完善以下信息):**
 - 设备: 小米11
 - 应用版本: 1.85.0-rc03

**额外信息**
1. 我只在委托页面和成就页面进行了测试，其他页面不清楚，但可能也存在这个问题。

**Comment by Ayagikei** [comment]
该问题将在 v1.85.0 正式版中进行修复。
