### ISSUE TITLE
[Feature] 其他日历的订阅功能

### ISSUE THREAD

**Issue by MistyMt** [Ayagikei/LifeUp#27]

**Comment by MistyMt** [comment]
例如滴答清单(TickTick)

**Comment by Ashkf** [comment]
确实有这种需求，对于已经有成熟的GTD系统，再迁移的成本有点大。Lifeup的特长在于其成就系统。

**Comment by Ayagikei** [comment]
感谢建议，
日历订阅和双向同步功能正在我们的开发计划中。

但因为我自身没怎么使用过类似的功能，目前还不确定具体的逻辑。
后续会先进行功能调研。

按照计划会支持系统日历和谷歌日历集成。

**Comment by MistyMt** [comment]
😘
