### ISSUE TITLE
[Feature] HTTP API to integrate with LifeUp

### ISSUE THREAD

**Issue by ChrisvanChip** [Ayagikei/LifeUp#28]
**Is your feature request related to a problem? Please describe.**
I can't safely integrate LifeUp with my applications and hobby projects. There's no official API documented and replaying HTTP requests for synchronization is inconvenient (as the data can change randomly).

**Describe the solution you'd like**
I'm looking for an official HTTP API to fetch the data from the cloud. Eventually, it would be awesome if I could save that data in the cloud too. So basically, documentation for the synchronization feature would be appreciated.

**Describe alternatives you've considered**
I can figure out the requests with localhost proxies & Fiddler, but this is inconvenient and the data can change anytime.

**Comment by Ayagikei** [comment]
LifeUp is an app that stores data offline, not in the cloud.
Currently its HTTP interface is only used for access to the "world" module.

Because there is no HTTP interface, there is currently no way to "open" API integration.
---
Currently you can back up data to WebDAV server/Drive/DropBox using the in-app backup function.
---
In the future, we may open the client interface, or provide a cloud data source access mode (this involves a lot of transformation and cannot be completed in the short term).

**Comment by ChrisvanChip** [comment]
> Currently you can back up data to WebDAV server/Drive/DropBox using the in-app backup function.

@Ayagikei Thanks for that! I'll create a parsing program to fetch the SQLite data from WebDAV. 

On the "Usage effects" section from shop items, there are several features like coin rewards & timers. Could a feature like "HTTP GET request" be added?

When I use the item in my inventory, I would like that LifeUp Pro sends a request to my server using HTTP GET. This webhook would allow me to create custom rewards.

**Comment by Ayagikei** [comment]
The "HTTP GET request" seems like a very cool idea!

And yes, we will consider it as an advance option (or maybe call it a geek option).

**Comment by ChrisvanChip** [comment]
> And yes, we will consider it as an advance option (or maybe call it a geek option).

@Ayagikei Do you have an ETA on this? It can really help my productivity.

**Comment by Ayagikei** [comment]
> > And yes, we will consider it as an advance option (or maybe call it a geek option).
> 
> @Ayagikei Do you have an ETA on this? It can really help my productivity.

Since we are developing in our spare time, there are many uncertainties.
It is difficult to provide estimates for features that are not going live in the most recent version.

But this function is actually not complicated.
If there is an update in the future, we will update this issue.

**Comment by Ayagikei** [comment]
We will be releasing the v1.90 soon.
**In this version, you can open a URL by using an item.**

And this is not limited to HTTP/HTTPS links. It is even possible to interact with other applications.

At the same time, we will also open some client APIs.

**Comment by Ayagikei** [comment]
We have released v1.90.
