### ISSUE TITLE
[Bug] Google Play Pass causes repeating "in app purchase product is error state" snackbar.

### ISSUE THREAD

**Issue by kcrawfordtaylor** [Ayagikei/LifeUp#29]
**Describe the bug**
"in app purchase product is error state" snack bar keeps popping up in app.

**To Reproduce**
1. Have Google Play Pass
2. Go to About page
3. Click "Buy the developers a coffee" and Confirm
4. Try doing it again (this step may be unnecessary)
5. Wait 30 seconds
6. Navigate to other pages of the app such as task view

**Expected behavior**
Snack bar doesn't appear. Or, it appears once and goes away forever.

**Screenshots**
![Screenshot_20220401-185213.png](https://user-images.githubusercontent.com/83239672/161355284-7b90b112-1e6c-4ec0-91cb-629b261d932b.png)
![Screenshot_20220401-185220.png](https://user-images.githubusercontent.com/83239672/161355288-d84ab5f0-9194-4cfa-8a42-244f7d990778.png)
![Screenshot_20220401-185520.png](https://user-images.githubusercontent.com/83239672/161355448-140008ac-9013-473e-9eba-2e116610c7a1.png)

Shows coffee as x1 but will go back to x0 after restarting the app.
![Screenshot_20220401-185648.png](https://user-images.githubusercontent.com/83239672/161355565-a789032e-7cd7-49ea-8a76-48dc41b1b9a5.png)

**Environments and Version (please complete the following information):**
 - Device: [e.g. Pixel 5]
 - OS: [e.g. Android 9.0]
 - Version [e.g. v1.84.0 (240) ]

**Additional context**
Things that I Have Tried:
- I've forced restarted the app a couple times.
- I have restored from backup files.
- I have uninstalled and reinstalled the app.

I still get the error after reinstalling from the play store and restoring from a backup. 

Unsure if this is related, but now whenever I start the app, I get a sync conflict. I have already chosen to overwrite the remote back up with the local backup once before. But it keeps popping up.

Might be best to disable buying coffee if you use Google Play Pass. It said it was included in my play pass subscription as it was an in app purchase and it showed the transaction was successful. 
![Screenshot_20220401-185947.png](https://user-images.githubusercontent.com/83239672/161355634-b81e6829-24bf-4df7-88da-bd16b8d21f7e.png)

**Comment by Ayagikei** [comment]
Thanks for the feedback.

We will fix this soon.

Coffee purchases shouldn't actually support Play Pass unlocking, it's probably a misconfiguration of the Play Pass team integration.

**Comment by Ayagikei** [comment]
As planned, we will release a small version in these two days to fix this problem.

You can check out for updates on Google Play recently.

Thanks again for the feedback!

**Comment by Ayagikei** [comment]
**The error message issue has been fixed in v1.88.1.**

The backup conflict problem is due to the post-restore comparison using information that was before the backup.
Just "skip" the conflict popup, or perform one more time "upload" operation.

We will also improve this issue in the v1.88.2 version.
