### ISSUE TITLE
任务链

### ISSUE THREAD

**Issue by syh6585** [Ayagikei/LifeUp#3]
可以增加任务链的功能吗？

有前置任务，后续任务的概念，要开启后续的任务，必须完成前置任务。

我觉得会比较适合 【学习某种技能】的场景。

**Comment by Ayagikei** [comment]
谢谢建议，确实有这种需求适合的场景。也挺符合游戏化的设定。

目前优化级可能不高，会排期处理。

**Comment by Ayagikei** [comment]
关于这一点，[我们目前通过 API 的方式来实现该功能。](https://wiki.lifeupapp.fun/zh-cn/#/guide/api)

如果不借助外部开发的话，在应用内可以通过使用特殊商品来实现创建任务。

搭配成就，你可以实现跟踪各种应用内指标，然后随之创建任务。
（比如力量达到10级 -> 奖励创建任务的商品 -> 创建任务）。
