### ISSUE TITLE
[Bug] The category of separation by day, week, month does not work well, it does not show the tasks as it should. I know this is experimental, I just wanted to comment on it. I use Android 9

### ISSUE THREAD

**Issue by N-a-i-r-o-b-i** [Ayagikei/LifeUp#34]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environments and Version (please complete the following information):**
 - Device: [e.g. Pixel 5]
 - OS: [e.g. Android 9.0]
 - Version [e.g. v1.84.0 (240) ]

**Additional context**

**Comment by Ayagikei** [comment]
Please provide details, screenshots, etc. according to the issue template.

**Comment by Ayagikei** [comment]
Without more information to provide, we will close this issue first.

The display of smart lists is currently in line with our expectations.
