### ISSUE TITLE
[Bug] Exp in Subtask Settings doesn't save

### ISSUE THREAD

**Issue by ever-balance** [Ayagikei/LifeUp#37]
**Describe the bug**
I'm trying to assign Exp to subtasks, but when I return to the task edit overview it doesn't seem to have saved, instead it shows the placeholder "Exp" text again. The coin setting does save.

**To Reproduce**
1. Create a new task
2. Add a new subtask to that task
3. Click the cog wheel behind the subtask
4. Fill in preferred Exp value
5. Return to main task overview
6. Go back to the subtask's settings

**Expected behavior**
I expected the Exp value to have saved and show.

**Environments and Version (please complete the following information):**
 - Device: Huawei P30 Lite 
 - OS: Android 10
 - Version v1.90.0

**Comment by Ayagikei** [comment]
Thanks for the feedback,
This problem can be reproduced.

But the save logic should be successful. It's just that the data is not displayed correctly when editing, which does not affect the normal use of this function.

We will fix them together after collecting a wave of v1.90 issues soon.

**Comment by Ayagikei** [comment]
**The issue has been closed in v1.90.1.**
