### ISSUE TITLE
[Feature]添加运动步数设置API (Add step count APIs)

### ISSUE THREAD

**Issue by zzndb** [Ayagikei/LifeUp#38]
**你的需求是否与某个问题相关联？请描述你遇到了什么问题。**
当前步数统计需要手动输入，或者计算（不过感觉有点迷，今儿早上起来就发现有快三千步，也不知道昨晚去哪儿梦游了

**描述你的解决方案**
不如提供API来设置步数，如果可以从其他渠道获取，就能有自动更新的能力

（如果有提供了API，目前自己准备的方案是从 Notify For Mi Band 拿步数，用 Tasker 来更新到人升。）

**Comment by Ayagikei** [comment]
感谢反馈，我们会考虑在近期版本加入该 API。

**Comment by Ayagikei** [comment]
久等了，v1.90.6 版本已经加入了该API。
https://docs.lifeupapp.fun/en/#/guide/api?id=set-the-number-of-steps
