### ISSUE TITLE
[Feature] API for overdue / given up tasks

### ISSUE THREAD

**Issue by CobraA1** [Ayagikei/LifeUp#39]
**Is your feature request related to a problem? Please describe.**
I'm trying to do some automation when a task is overdue / given up. Would be nice to have an API for that.

**Describe the solution you'd like**
Creation of API(s) for when a task is given up or declined when overdue.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by Ayagikei** [comment]
**Thanks for your suggestion!**

We will consider adding both event notifications.

In fact, v1.90.2 already includes overdue notifications.
But it's not fully tested, so it hasn't been updated in the documentation.
And its return value is an array, we have not tested whether Tasker can receive it.


But you can take it a try:
**name:** app.lifeup.task.overdue

**return values**:
| Parameters | Meaning             | Examples                        |
| :--------- | :------------------ | :------------------------------ |
| task_ids   | task id array       | [1, 2, 3]                       |
| task_gids  | task group id array | [1, 2, 3]                       |
| Names      | task name array     | [Getting started, Drink Waters] |

**Comment by CobraA1** [comment]
Is there a way to test overdue tasks without having to wait a day?

**Comment by Ayagikei** [comment]
> Is there a way to test overdue tasks without having to wait a day?

Maybe you can create some testing tasks that will be overdue after a few minutes.

**Comment by Ayagikei** [comment]
> **Thanks for your suggestion!**
> 
> We will consider adding both event notifications.
> 
> In fact, v1.90.2 already includes overdue notifications. But it's not fully tested, so it hasn't been updated in the documentation. And its return value is an array, we have not tested whether _Tasker_ can receive it.
> 
> But you can take it a try:
> 
> **name:** app.lifeup.task.overdue **return values**:
> 
> Parameters	Meaning	Examples
> task_ids	task id array	[1, 2, 3]
> task_gids	task group id array	[1, 2, 3]
> names	task name array	[Getting started, Drink Waters]

We have released version **v1.90.3 and added notifications for given-up tasks.**

At the same time, [we have also updated the documentation.](https://docs.lifeupapp.fun/en/#/guide/api?id=task-given-up)

If you have other suggestions for APIs, feel free to open new issues.
