### ISSUE TITLE
[Feature] Ability to query for any attribute

### ISSUE THREAD

**Issue by CobraA1** [Ayagikei/LifeUp#44]
**Is your feature request related to a problem? Please describe.**
**Describe the solution you'd like**

Being able to query any of the attributes would be nice for being able to create something like a widget in KWGT (which can be updated via Tasker) so I can see them outside of the app.

**Describe alternatives you've considered**

Alternatively, a widget for showing the attributes would be nice. If so, I'd like to be able to select which attributes to show in the widget.

**Comment by Ayagikei** [comment]
We have already added the API in v1.90.6.

Please check the document for detail:
[https://docs.lifeupapp.fun/en/#/guide/api?id=query-attributes](https://docs.lifeupapp.fun/en/#/guide/api?id=query-attributes)
