### ISSUE TITLE
[Feature] Hi again bro, thank you for your previous warm response! Lately I was trying to figure out if there's a URL action that could trigger "using an item", not only purchasing it.

### ISSUE THREAD

**Issue by Khozoa** [Ayagikei/LifeUp#46]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Ayagikei** [comment]
Hi, these two issues seem to have been created accidentally. I will close them first.
