### ISSUE TITLE
[Feature] API: Go to a shop item in the shop via linkpress. 

### ISSUE THREAD

**Issue by HunterArmstrong** [Ayagikei/LifeUp#49]
**Is your feature request related to a problem? Please describe.**

I want there to be a parameter on the "jump" function of the APIs of LifeUp where you can jump to a shop item in the shop to buy it and use it.
I want this because I want to be able to add a shortcut to my home screen on Android that takes me to an item in the item shop.

**Describe the solution you'd like**

I think that maybe the parameters could be:

lifeup://api/goto?**page=item**&**item_id=[item_id]**

The **page=Item** parameter could be the item page.
Like this:
![Screenshot_20221114-094312_LifeUp Pro](https://user-images.githubusercontent.com/57189836/201729353-210eaf1f-b9e5-4f34-a25f-75b79253a635.jpg)

And **item_id=[item_id]** could be the specified item ID number that you want to go to

Example:
lifeup://api/goto?page=Item&item_id=15

I hope you consider my request and that you have a wonderful day! :)

**Comment by Ayagikei** [comment]
Thanks for your suggestion!

We will consider it, maybe in the following few versions.
The current goto API does have a lot of room for expansion.
Jumping directly to the specified page is also simpler than additional implementation.

**Comment by Ayagikei** [comment]
Sorry for the late reply.

Actually, the API has been added in v1.91.0.

You can try something like this:
`lifeup://api/goto?page=purchase_dialog&id=1`

> the id is the item id
