### ISSUE TITLE
[Feature]  Add option to change end of day

### ISSUE THREAD

**Issue by KierPrev** [Ayagikei/LifeUp#51]
Sometimes the routine of people end AFTER midnight, and you can do some task in that time, but the app already count the tasks as overdue.

**Request**:
Add a settings option to change the reset time from 00:00 to a custom time.

Thank you!

**Comment by KierPrev** [comment]
Closing this because I'M DUMB.

The option to adjust the exact hour of the deadline is in each task option.

**Comment by Ayagikei** [comment]
Hello,
Glad you found the solution! :)

By the way, LifeUp also provides a global option for new tasks.
You can check [https://docs.lifeupapp.fun/en/#/guide/faq?id=how-to-make-tasks-not-overdue-at-0-oclock](https://docs.lifeupapp.fun/en/#/guide/faq?id=how-to-make-tasks-not-overdue-at-0-oclock) for details.

**Comment by KierPrev** [comment]
Oh, thank you!  That's useful ☺️  Now I'm helping the Spanish translation on CrowIn. Maybe some day I could help translating the wiki too?

**Comment by Ayagikei** [comment]
> Oh, thank you! That's useful ☺️ Now I'm helping the Spanish translation on CrowIn. Maybe some day I could help translating the wiki too?

Hello, thanks for helping with the translation!
We will bring the latest translated text with each update.

As for the wiki, we haven't found a suitable translation hosting site yet (we might see if we can use Crowdin) and a suitable multilingual switching solution. It is currently written in markdown, and you can also find all source files of the wiki at [https://github.com/Ayagikei/LifeUp-Wiki/tree/master/docs/en](https://github.com/Ayagikei/LifeUp-Wiki/tree/master/docs/en).

Of course, you can also translate the source files directly, we will try to handle it manually.

**Thank you again for your help!**
