### ISSUE TITLE
[Feature] More buttons for Confirm Dialog

### ISSUE THREAD

**Issue by Agonar35** [Ayagikei/LifeUp#52]
**Is your feature request related to a problem? Please describe.**
Confirm Dialog can be used for choosing between different rewards, but currently we can only choose between two options (positive and negative). If we want to choose between 3 or 4 options it's not possible.

**Describe the solution you'd like**
Programming more optional buttons to enrich the API and renaming the current buttons as button1 and button2 or something similar to make way for new buttons (button3, button4...)

**Describe alternatives you've considered**
A new sub system for the shop, in which we can create subfolders of items which should be contained in other main items. For example: if I've got an item named Fisherman, it would be nice being able of clicking on it to display a list of items and choose between different products that a fisherman would sell, each item could have a different price, stock or conditions just as a normal object, but it would be contained in their respective "shop", something similar to a category but without involving necessarily the use of categories. 

**Additional context**

**Comment by Agonar35** [comment]
I've been thinking and the option of the sub system for the shop would be more user friendly for those who doesn't know how to use the APIs, I mean, I'm still learning about it and I think it's the most powerful option for the future of this APK, but not all the users are willing to learn to use the APIs.

**Comment by Ayagikei** [comment]
Hello, we think the "Fisherman" you mentioned can be covered by the "synthesis system".

The synthesis function is used for any item exchange (this also covers the ability to customize the store). For details, please refer to the tutorial ([https://docs.lifeupapp.fun/en/#/guide/hello_lifeup?id=_1-synthesis-crafting](https://docs.lifeupapp.fun/en/#/guide/hello_lifeup?id=_1-synthesis-crafting)).

---

As for the API, its positioning is advanced functions. And it can be used for secondary development.

Confirm Dialog API will add an option. But would not consider adding more. (The Dialog component we currently use only supports up to 3 operations).

**Comment by Ayagikei** [comment]
We have added the `neutral_text`, and `neutral_action` params to the `confirm_dialog` API.

For more details, please check [https://docs.lifeupapp.fun/en/#/guide/api?id=confirm-dialog](https://docs.lifeupapp.fun/en/#/guide/api?id=confirm-dialog)

By the way, we also slightly improved the controllability of the API. If you don't provide a text and action for a button, the button will be hidden by default.
