### ISSUE TITLE
[Feature] Hide categories

### ISSUE THREAD

**Issue by Agonar35** [Ayagikei/LifeUp#54]
**Is your feature request related to a problem? Please describe.**
I've got many items that doesn't meet the skill condition to be bought and I created a category for those items and others that can't be bought for other reasons. Sadly I can't choose which categories do I want to see and which categories I don't want to be shown in my shop.

**Describe the solution you'd like**
To introduce the option of hiding some categories from our shop just as we can hide the non buyable items

**Describe alternatives you've considered**
Currently, the non buyable and sold out items can be hidden, but not those which are not on sale because you don't meet a skill level. It would be nice being able of hiding those items too as long as you can't buy those because of your low skill level. Those items would appear again automatically in the shop once you meet the level requeriments.

**Comment by Ayagikei** [comment]
Hello, we will consider this.

Both solutions seem to work.

We will give priority to the "hide categories" feature.
