### ISSUE TITLE
[Bug] Level-down broadcast isn't working

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [Ayagikei/LifeUp#57]
**Describe the bug**
The level down broadcast isn't working, and I even made sure the action name was spelled correctly in Tasker (`app.lifeup.level.down`) and that broadcasts were enabled in the app's settings. All the other broadcasts work fine for me, it's just *this one* that's not happening.

**Expected behavior**
The broadcast is supposed to be received by Tasker, but absolutely nothing is happening.

**Environments and Version (please complete the following information):**
 - Device: Motorola Moto z4
 - OS: Android 10 (QDF30.130-42-5-17)
 - Version 1.90.9

**Comment by Ayagikei** [comment]
Hello, Thanks for the feedback.

We will check it later. It may be that the implementation logic of the broadcast is abnormal.

**Comment by Ayagikei** [comment]
We confirmed that the problem does exist.

There is an error in the judgment statement about it.

We will fix this problem in the next version.

Since we are preparing a development feature version, the timing of the release is still to be determined.

**Comment by UsernamesAreNotMyThing** [comment]
In a related issue, I've also noticed that the attribute query broadcast sometimes leaves the `total_exp` extra unset, or at least this is how it appears in Tasker.

**Comment by Ayagikei** [comment]
> In a related issue, I've also noticed that the attribute query broadcast sometimes leaves the `total_exp` extra unset, or at least this is how it appears in Tasker.

Hi, thanks for the feedback.

We confirmed the code implementation here, `total_exp` should be always assigned and not null.

We suspect this is a receive issue on the tasker side.

**Comment by Ayagikei** [comment]
Sorry for the long wait.

We have fixed the issue in v1.91.
