### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by liufuxing** [Ayagikei/LifeUp#59]
开发者你们好。你们的API调用的功能我非常喜欢，希望可以增加一些电脑端也可调用的API

**Comment by Ayagikei** [comment]
你好，所有 API 都能通过《云人升》使用 HTTP 协议进行调用。

详情请查看【实验】-【云人升】或者相关的 Github 仓库：
[https://github.com/Ayagikei/LifeUp-SDK](https://github.com/Ayagikei/LifeUp-SDK)
