### ISSUE TITLE
Timed Rewards

### ISSUE THREAD

**Issue by HunterArmstrong** [Ayagikei/LifeUp#6]
For LifeUp I think there should be a timer use effect for rewards. This would be good for people who want to put a limit on the amount of time they are using on what would be a reward.

**Comment by Ayagikei** [comment]
**Thanks for your suggestion.**

We will plan to develop this feature in the near future. (in the next 1~2 feature update if possible)
It will be a nice feature :)

**Comment by HunterArmstrong** [comment]
Thanks!! Keep up the good work ✌️❤️

**Comment by Ayagikei** [comment]
Added the countdown timer effect in v1.82.0
