### ISSUE TITLE
API: Moving coins to ATM

### ISSUE THREAD

**Issue by roguecat0** [Ayagikei/LifeUp#60]
Could you add an API to move coins to your ATM and also from your ATM to the outside?
Thank you.

**Comment by Ayagikei** [comment]
Of course, thanks for the suggestion!

We will consider adding this API in the next version.

**Comment by Agonar35** [comment]
It would be nice adding more features to the current shop settings API too. I mean, adding or subtracting coins from the ATM directly, not swapping from 'pocket' to ATM but adding or subtracting like this:

Lifeup://api/shop_settings?key=atm_balance=-50&atm_balance_type=relative

**Comment by Ayagikei** [comment]
> It would be nice adding more features to the current shop settings API too. I miss adding or subtracting coins from the ATM directly, not swapping from 'pocket' to ATM but adding or subtracting like this:
> 
> Lifeup://api/shop_settings?key=atm_balance=-50&atm_balance_type=relative

Get it.
We will also take this into consideration.

**Comment by Ayagikei** [comment]
We have added the ATM-related API and the API to direct set the ATM Balance.

For details, please check [https://docs.lifeupapp.fun/en/#/guide/api?id=atm](https://docs.lifeupapp.fun/en/#/guide/api?id=atm) and [https://docs.lifeupapp.fun/en/#/guide/api?id=shop-settings](https://docs.lifeupapp.fun/en/#/guide/api?id=shop-settings)

Thanks again for your suggestion!
