### ISSUE TITLE
[Feature] Url to enable or disable an item

### ISSUE THREAD

**Issue by Agonar35** [Ayagikei/LifeUp#63]
**Is your feature request related to a problem? Please describe.**

It's not possible to enable or disable the availability of an object using URLs. It's possible to modify the stock number, which has a similar effect, but once you modify the stock number, you can't switch again to the unlimited option, except if you do it manually.

**Describe the solution you'd like**

A new function for the API (Item) in which we can specify if we want to enable or disable the purchase of an object

Something like: lifeup://api/item?id=300&available=true

If false, the item wouldn't be purchasable.

**Comment by Ayagikei** [comment]
Hello, thanks for raising the issue.

We will consider adding it in the next version.

**Comment by Ayagikei** [comment]
We have added it in v1.91.

Please check the [https://docs.lifeupapp.fun/en/#/guide/api?id=edit-items](https://docs.lifeupapp.fun/en/#/guide/api?id=edit-items) for details.

And thanks for your suggestion again!
