### ISSUE TITLE
New API

### ISSUE THREAD

**Issue by ShadowYourFriend** [Ayagikei/LifeUp#64]
I would like to suggest implementing a broadcast api about countdown where you could track when a countdown has ended using tasker.

**Comment by Ayagikei** [comment]
Hello, thank you for raising the issue!

We may provide an API for the countdown (or including starting and pausing).
We're not sure if you're referring to the Pomodoro countdown or the item countdown, but we'll consider both.

**Comment by ShadowYourFriend** [comment]
I'm sorry! I was referring to the item countdown

**Comment by ShadowYourFriend** [comment]
> I'm sorry! I was referring to the item countdown

And thank you for looking into my feedback😊

**Comment by Ayagikei** [comment]
> I'm sorry! I was referring to the item countdown

Get it. :D

**Comment by Ayagikei** [comment]
Sorry for keeping you waiting!

**We have added the API in v1.91.1.**

You can check the document for details and if it suits your needs:
[https://docs.lifeupapp.fun/en/#/guide/api?id=shop-item-countdown](https://docs.lifeupapp.fun/en/#/guide/api?id=shop-item-countdown)
