### ISSUE TITLE
[Bug] Some dialogs aren't usable in landscape on phones

### ISSUE THREAD

**Issue by UsernamesAreNotMyThing** [Ayagikei/LifeUp#65]
# Describe the bug
The buttons in certain dialogs, notably those for purchasing or using shop items, can't be seen or clicked if the full content of the dialog can't all fit on screen, and there is no way to scroll down to get there either.

## To Reproduce
1. Click the "buy" button for a shop item in landscape mode - you won't be able to use or see any of the buttons on the dialog

## Expected behavior
The dialog should *at least* be able to scroll, which can be implemented really easily by using a `ScrollView` as the root view of the dialog and setting the existing dialog content as a child of that.

## Screenshots

![Screenshot_20230207-132415](https://user-images.githubusercontent.com/92757918/217332860-0b6a7bbe-7258-422d-baf7-cdeb74729734.png)

### Environments and Version (please complete the following information):
 - Device: **Motorola Moto z4**
 - OS: **Android 10** (QDF30.130-42-5-17)
 - Version: **v1.90.9** (400)

**Comment by Ayagikei** [comment]
Thanks for the feedback!

We'll investigate it.

**Comment by UsernamesAreNotMyThing** [comment]
Just discovered that this still occurs on the dialogs for editing coin and synthesis effects on items, and for returning items.

**Comment by Ayagikei** [comment]
> Just discovered that this still occurs on the dialogs for editing coin and synthesis effects on items, and for returning items.

Get it. We will check that again.

**Comment by Ayagikei** [comment]
> Just discovered that this still occurs on the dialogs for editing coin and synthesis effects on items, and for returning items.

These dialogs already support scrolling in v1.93.0-rc02.

If you find a new exception dialogs, please feel free to re-open the issue.
