### ISSUE TITLE
[Feature]输入步数时默认使用数字键盘

### ISSUE THREAD

**Issue by AnLazyOtter** [Ayagikei/LifeUp#75]
**你的需求是否与某个问题相关联？请描述你遇到了什么问题。**
希望在手工录入步数时，能自动切换到数字键盘。

**描述你的解决方案**
在状态-运动卡片中，点击输入步数后，自动将虚拟键盘切换到输入数字的状态。

**描述可选方案**
构建一个输入纯数字的自定义虚拟键盘。

**额外信息**
截图：是指如图的计步输入。
![Screenshot_2023-03-19-22-05-12-718_net sarasarasa lifeup](https://user-images.githubusercontent.com/40395191/226181360-45fa23c3-6ccd-48d2-acf3-4b10a932ad15.jpg)

最后想额外问一下：
计步是指运行期间获取到的步数，还是指每次启动获取下系统今日记录的步数呢？

**Comment by Ayagikei** [comment]
收到，感谢反馈！

**Comment by Ayagikei** [comment]
The issue should be fixed in v1.91.1

**Comment by Ayagikei** [comment]
抱歉才看到提问：
> 最后想额外问一下：
> 计步是指运行期间获取到的步数，还是指每次启动获取下系统今日记录的步数呢？

LifeUp 中的步数是通过总数的差值，尽量计算出**今日步数**。系统并没有提供API直接获取每日步数（至少在我们开发该功能时没有）。详情可以点击步数模块上的“问号”查看说明。
