### ISSUE TITLE
[Feature] 重点是商店的一些机制的需求

### ISSUE THREAD

**Issue by xwxb** [Ayagikei/LifeUp#79]
**你的需求是否与某个问题相关联？请描述你遇到了什么问题。**
我对 LifeUp 的设计想法还是很看好的，一直想建立自己的一个动机体系，软件也是卸载删除好几遍，近期才有效用下来了一整子。
就是我用本软件建立的动机体系，可能和软件本身的设计想法有很多冲突的地方，所幸软件保留了一定自定义性，所以我还是正常用了下去。但是还是想在一些地方增加自定义性。

1. 取消“状态”体系的选项，就是有六属性的那个。因为我目前只保留了委托和商店两大块，所以属性我根本就用不上，我动机体系的建立就是在“自己本就想要这样一个记录”的基础上慢慢增加。不过说实话我自己都知道这个这个有点伪需求哈哈，可以作为一个考虑吧。我知道完全可以不管这个，但是在任务里面和逾期波动的时候会变化总是有点强迫症。
2. 增强金币“自动设置”的自定义性。这个我之前还挺需要的，就是想控制不同难度和重要程度对应的金币数。现在倒是慢慢能适应起来了。
3. 其实主要想提出来的是有关商店的几个修改，上面两点仅供参考，可以不用太在意。因为我重点用的就是商店的记录功能，算是这块的比较重度的用户了。

a. 增加随机图标的选择，增加新鲜感；
b. 因为我的商品大多数都是单件的，我希望也能像任务设置一样能够记忆保留上一次的数量选择；
c. 售罄机制我觉得很…有点不合理，可能只是我个人想法的问题。我个人理想的情况是售罄的商品直接消失就好了，或者单独给商店加个“下架商品”的区域，还能方便重新上架；不然我还得手动移动到一个清单里面。

edit: 又看了一下，反而是仓库的东西可以重新上架。这个我也不太理解emm？总感觉买到手的东西给又还给商店供货是个什么情况。

抱歉没按格式来，想法比较乱，重点关注最后几句话就好了，开发辛苦了。

**Comment by Ayagikei** [comment]
抱歉回复晚了，前段时间工作有点太忙了（

1. 我们近期也在考虑增加功能模块的总开关（属性模块、商店模块、成就模块）。

2. 自动设置是一条简单的计算公式。但技术上也不好支持自定义，这一点可能需要后面再找找好一点的解决方案。

3. 
a. 这一点感觉需求会有点偏，我们后续再根据反馈作评估。

b. 这里不太确定是哪里的数量选择？

c. 最初的售罄设定就是直接下架的。但是遇到的反馈反而更多，所以改为了二次确认。

我们会评估是否要增加一个“售罄”清单或者一键转入的设定。

**Comment by xwxb** [comment]
> 抱歉回复晚了，前段时间工作有点太忙了（
> 
> 1. 我们近期也在考虑增加功能模块的总开关（属性模块、商店模块、成就模块）。
> 2. 自动设置是一条简单的计算公式。但技术上也不好支持自定义，这一点可能需要后面再找找好一点的解决方案。
> 
> a. 这一点感觉需求会有点偏，我们后续再根据反馈作评估。
> 
> b. 这里不太确定是哪里的数量选择？
> 
> c. 最初的售罄设定就是直接下架的。但是遇到的反馈反而更多，所以改为了二次确认。
> 
> 我们会评估是否要增加一个“售罄”清单或者一键转入的设定。

1. 这个能加入就再好不过了，我还是倾向于需要这个功能的。
2. 这个功能需求度目前确实不是很高，增设反而感觉会造成软件的易用性下降。个人觉得以后如果有类似于“高级设置 / 强自定义性模式”的话可以考虑一下
3. ..
a. 嗯嗯，这点您可以关注一下。反正我个人是觉得，就类似于用 Notion 的时候添加 emoji 一样，要么就是通过搜索找到对应的，大多数时候就是随机一个增强观感。要是没有这个的话可能就直接用默认的了，因为反正就是一次性的。
b. 就是指商品的数量。比如说我上次这个商品是数量是1，下次希望保留商品数量是“自定义”（而不是“无限”）然后数量是1 。


c. 我个人猜测反馈增加的原因是可能是因为早期核心用户更倾向于构建类似 habitica 这种沉浸式游戏人生体系，所以“无限商品”是默认考虑的，也因为如此才设计成默认选项的。所以虽然这算是比较个人化的一个需求，但是还确实是我的核心需求，所以单独拿出来说一下。
我不确定您说的”二次确认“确认是什么意思。反正我现在的使用体验是售罄的商品好像就纯粹占地方，只有通过”改设置“和”编辑“这种割裂感的做法才能实现”重新上架”或者“移除归档”。
我个人认为“记忆上次商品的数量设定” + “下架区“的设定 是能兼顾您说的“反馈增加的”那些用户的，这里您也可以关注一下。
