### ISSUE TITLE
[Feature] Daily Step Count Statistics Chart

### ISSUE THREAD

**Issue by SavainB** [Ayagikei/LifeUp#85]
Hello i like what you do !
I like the recent update but i noticed that you donr show the number of steps, can you add it again

**Comment by Ayagikei** [comment]
Hi, thank you for your support and feedback!

Let me first explain why we haven't migrated step statistics yet:
LifeUp's step count is a small exploration in the early stage, showing the effect of its reward linkage reality.

But with the development of LifeUp, it exposed a lot of problems: the automatic step count is not accurate (especially the system restrictions such as non-Pixel), lack of ability to manage history records (although there is an API now).

As a result, step statistics are difficult to maintain.
At present, there are many accurate and easy-to-maintain health applications at the system level.

We wanted to know, how are you currently using this feature?
We may need to do further evaluation.

**Comment by SavainB** [comment]
What I liked the most was the fact that it showed me the number of steps per day, the history, and the fact that the automatic step count is not entirely accurate doesn't bother me much. However, the historical tracking of steps per day, week, and month was a really interesting statistic.
Since I installed Google Fit, I don't know why, but the step count has remained the same and become more accurate.

**Comment by Ayagikei** [comment]
> What I liked the most was the fact that it showed me the number of steps per day, the history, and the fact that the automatic step count is not entirely accurate doesn't bother me much. However, the historical tracking of steps per day, week, and month was a really interesting statistic. Since I installed Google Fit, I don't know why, but the step count has remained the same and become more accurate.

Thanks for your feedback!

We'll consider adding it back.

**Comment by Ayagikei** [comment]
We've added it back in v1.92.2.

If you haven't received the update yet, you may still have to wait a short while.

**Comment by SavainB** [comment]
Thanks its nice !!
