### ISSUE TITLE
[Bug] Tasks sometimes switch order randomly

### ISSUE THREAD

**Issue by Khotul** [Ayagikei/LifeUp#86]
**Describe the bug**
It's happened at least five times already and it's very frustrating.
Basically every once in a while tasks in all lists just randomly switch order for no apparent reason. The "sort" remains set to "custom", and only way to reverse that is to load an older backup. Pretty frustrating since I either have to reorder all lists again manually, or lose progress.

**To Reproduce**
I either have no idea what causes it, or it's inconsistent. At first I thought it was swiping, since first time it happened was after I tried swiping tasks instead of clicking them. But since that time I already disabled swiping tasks in settings yet it still happens.

One time it happened when I finished two tasks before the app "processed" the first task finishing (I clicked to finish the second task before the window with rewards from first task displayed), however when I repeated the same thing it didn't happen.

Another time I created a new list and tasks on all lists switched order randomly. But when I tried replicating this it didn't happen.

**Expected behavior**
The tasks shouldn't reorder randomly.

**Environments and Version (please complete the following information):**
 - Device: [Xiaomi Redmi 5 Plus]
 - OS: [Android 7.1.2]
 - Version [v1.92.1 (481) Pro]

**Additional context**
Happened since 1.91 at least

**Comment by Ayagikei** [comment]
In theory, it is impossible for LifeUp's list to be sorted "randomly".

Actions like completing tasks also don't change the custom sort by.

We suspect that the problem you describe is due to a custom sort by which LifeUp maintains.
This means that if you adjust the sorting in the smart list (such as "All", "Daily"), theoretically the original list will also be modified synchronously.

Please provide the following information:
- Have you unchecked [Group by list] on the [Settings] - [Labs] - [Smart List] page?
- Please continue to locate the happen timing of the problem.

**Comment by Khotul** [comment]
Update: it happened again today, however I have no idea what caused it.

What I did notice however is that you are right, the tasks don't rearrange order randomly, they rearrange themselves in the alphabetic ascending way. But the "sort" option is still set to "Custom".

I disabled smart list back when I first noticed this issue happening, so yes it keeps happening with Smart List turned off.

When tasks switch order they do so on every single list. 

For example in my daily list I have tasks grouped in the order I do them every day:
- Wake up before 1 pm
- Check email
- Eat Breakfast
- Brush teeth
etc etc

Today this order changed to
- Brush teeth
- Check email
- Eat breakfast
- Wake up before 1 pm
(with others in between obviously)

Also, because daily tasks get hidden by default after completion, I often notice the order got switched next day, which is why it's hard for me to pinpoint what causes it.
I enabled "do not fold any tasks" option and will update you once I have any more info.

If you do find something, please tell me cause this bug's annoying a lot.

**Comment by Ayagikei** [comment]
> Update: it happened again today, however I have no idea what caused it.
> 
> What I did notice however is that you are right, the tasks don't rearrange order randomly, they rearrange themselves in the alphabetic ascending way. But the "sort" option is still set to "Custom".
> 
> I disabled smart list back when I first noticed this issue happening, so yes it keeps happening with Smart List turned off.
> 
> When tasks switch order they do so on every single list.
> 
> For example in my daily list I have tasks grouped in the order I do them every day:
> 
> * Wake up before 1 pm
> * Check email
> * Eat Breakfast
> * Brush teeth
>   etc etc
> 
> Today this order changed to
> 
> * Brush teeth
> * Check email
> * Eat breakfast
> * Wake up before 1 pm
>   (with others in between obviously)
> 
> Also, because daily tasks get hidden by default after completion, I often notice the order got switched next day, which is why it's hard for me to pinpoint what causes it. I enabled "do not fold any tasks" option and will update you once I have any more info.
> 
> If you do find something, please tell me cause this bug's annoying a lot.

> 

Thanks for the info!

We'll also try to investigate and see if we can find anything.

**Comment by Khotul** [comment]
So it hasn't happened these past few weeks, I thought that it maybe was accidentally fixed and the app auto-updated, but now I think I know why it hasn't happened.

I made a new list and moved some tasks from one list to that new one.


After that action every single list (including those I didn't even touch) reordered itself into the "alphabetic" sorting, despite the option still being checked at "custom". Smart list disabled.

Including those lists I didn't even touch - I moved some tasks from list 3 to list 4 but the lists 1 and 2 also reordered.


The issue itself isn't realted to making new lists (unless that is another cause too), cause it happened more times than the amounts of lists I have. I think it may be something related to moving tasks? Maybe editing/creating new ones? I'm not sure

The reason it hasn't happened these past few weeks is probably because I stopped adding new tasks or editing old ones. I already had everything important I do in the app, I didn't need to add new stuff until today.

**Comment by Ayagikei** [comment]
A small update based on feedback from other users.

He encountered the problem of setting "Sort by deadline" but it didn't take effect.

We discovered a strange condition in sorting, and we will fix it in v1.93.0.

We're still not sure if this is related to the issue, so we'll keep watching.

**Comment by Khotul** [comment]
> A small update based on feedback from other users.
> 
> He encountered the problem of setting "Sort by deadline" but it didn't take effect.
> 
> We discovered a strange condition in sorting, and we will fix it in v1.93.0.
> 
> We're still not sure if this is related to the issue, so we'll keep watching.

Hi, I've just updated to the new version and I've noticed a major improvement. 

The bug did still happen, **however** clicking "sort -> custom" reverted the bug changing the sorting. Had to manually press it on every single list still, but it's much better than rearranging every task manually on every single list.

Not closing this cause technically the issue is still happening, it's just much more easier to revert now. Still, that's a major improvement and I'm happy with it.

Many thanks for this <3

**Comment by Ayagikei** [comment]
> > A small update based on feedback from other users.
> > He encountered the problem of setting "Sort by deadline" but it didn't take effect.
> > We discovered a strange condition in sorting, and we will fix it in v1.93.0.
> > We're still not sure if this is related to the issue, so we'll keep watching.
> 
> Hi, I've just updated to the new version and I've noticed a major improvement.
> 
> The bug did still happen, **however** clicking "sort -> custom" reverted the bug changing the sorting. Had to manually press it on every single list still, but it's much better than rearranging every task manually on every single list.
> 
> Not closing this cause technically the issue is still happening, it's just much more easier to revert now. Still, that's a major improvement and I'm happy with it.
> 
> Many thanks for this <3

Glad it helps!

Based on your description, there is something we want to confirm.

When you have a problem with sorting, enter the corresponding list and click Sort. Is the currently selected value displayed as "Custom"?

At the same time, please also pay attention to whether the forward and reverse order in the upper right corner is as expected.

Thanks again for your feedback!

**Comment by Ayagikei** [comment]
Hello, we have some new discoveries.

We received feedback from a user about a similar problem. Based on the video she provided, we found that the order of tasks was reversed.

LifeUp's custom sorting of tasks should always maintain a positive order as expected.

**We will fix this issue in v1.93.0-rc03.**
This version is currently submitted to Google Play for review.

**Comment by Ayagikei** [comment]
Since this issue has not been reported recently, we will close it first. If the problem recurs, feel free to reopen it.
