### ISSUE TITLE
[Feature] search habit in history

### ISSUE THREAD

**Issue by SavainB** [Ayagikei/LifeUp#89]
It would be beneficial if you could incorporate a feature that allows users to search for habits by name in history. This would greatly assist me, as I currently have to manually scroll through all my habits to find a specific one. I believe that adding this functionality would greatly enhance the user experience."

![Screenshot_2023-09-05-21-59-28-910_net sarasarasa lifeup](https://github.com/Ayagikei/LifeUp/assets/73843086/c96ee451-ebdf-4b68-a644-75ef9471e2e8)

**Comment by Ayagikei** [comment]
Hi, thanks for your advice!

It is in our development plan. We will try to release it in the next feature versions.

**Comment by Ayagikei** [comment]
This change is planned to be released with the v1.93.0 version.

We are currently rolling out this release.

**Comment by Ayagikei** [comment]
v1.93.0-rc02 has been generally released and this feature has been added.

If there are any problems with it, please feel free to raise a new issue.
