### ISSUE TITLE
[Feature] Make a task for your friend/gf

### ISSUE THREAD

**Issue by depocoder** [Ayagikei/LifeUp#94]
**Is your feature request related to a problem? Please describe.**
 I want to assign some tasks and get tasks from gf, friend to do something like wash the floor or wash dishes.

**Describe the solution you'd like**
I think it will be cool if you create projects with invites for your friends and you can assign tasks to your friends.

**Additional context**
Glad to ask any questions

**Comment by Ayagikei** [comment]
This seems to be a duplicate of https://github.com/Ayagikei/LifeUp/issues/41.
