### ISSUE TITLE
[Bug] Can't open LifeUp's inventory page via API call in MacroDroid

### ISSUE THREAD

**Issue by LordElamak** [Ayagikei/LifeUp#99]
I've created a MacroDroid widget which should open the LifeUp inventory page with API call
lifeup://api/goto?page=main&sub_page=inventory
Unfortunately, LifeUp only opened shop page with previous open list

I've also tried with other calls from MacroDroid:
1.) lifeup://api/goto?page=main&sub_page=inventory&category_id=-1
     result: LifeUp only opened shop page with previous open list
2.) lifeup://api/goto?page=main&sub_page=shop
     result: works as expected - LifeUp opened shop page with previous open list
3.) lifeup://api/goto?page=main&sub_page=shop&category_id=-1
     result: works as expected - LifeUp opened shop page with "All" list

Then I also tried the "lifeup://api/goto?page=main&sub_page=inventory" call with a shop item (closed LifeUp app, activated the item via shop widget). It works as expected - LifeUp opened the inventory page.

It seems that the API call for the inventory page does not work from external source, at least not from MacroDroid.

 - Device: Samsung Galaxy A51
 - OS: Android 13
 - Version: 1.92.2 (487)
 - MacroDroid-Version : 5.37

**Comment by Ayagikei** [comment]
Get it.

Thanks for the information and the bug report!

**Comment by Ayagikei** [comment]
We were able to reproduce the issue.

It will be fixed in v1.93.0 (maybe v1.93.0-rc01).

**Comment by Ayagikei** [comment]
This problem should have been fixed in v1.93.0-rc02.

If the problem persists, please feel free to open the issue again.
